server:
  port: 9999
  context-path: /
  
security:
  user:
    name: admin
    password: itcgs123
  oauth2:
    client:
      client-id: itcgs
      client-secret: s73v8wc0wqudc83bv920
      scope: read, write
      auto-approve-scopes: .*
    authorization:
      check-token-access: permitAll()

logging:
  level:
    org.springframework.security: DEBUG
  file: /var/log/itcgs-auth.log